## Initialising

In [1]:
import pandas as pd

df = pd.read_csv("dataset/student_performance_dirty.csv")

In [2]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index,Notes
0,7.0,99,Yes,9.0,1,91.0,excellent
1,4.0,82,No,4.0,2,65.0,review
2,8.0,51,Yes,7.0,2,45.0,review
3,5.0,52,Yes,5.0,2,36.0,excellent
4,7.0,75,No,8.0,5,66.0,review

In [3]:
df = df.drop('Notes', axis = 1)

In [4]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7.0,99,Yes,9.0,1,91.0
1,4.0,82,No,4.0,2,65.0
2,8.0,51,Yes,7.0,2,45.0
3,5.0,52,Yes,5.0,2,36.0
4,7.0,75,No,8.0,5,66.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10005 entries, 0 to 10004
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     8973 non-null   float64
 1   Previous Scores                   10005 non-null  int64
 2   Extracurricular Activities        10005 non-null  object
 3   Sleep Hours                       9509 non-null   float64
 4   Sample Question Papers Practiced  10005 non-null  int64
 5   Performance Index                 10005 non-null  float64
dtypes: float64(3), int64(2), object(1)
memory usage: 469.1+ KB

In [6]:
df.isnull().sum().sum()

np.int64(1528)

In [7]:
df.duplicated().sum()

np.int64(98)

In [12]:
df = df.drop_duplicates()

In [13]:
df.duplicated().sum()

np.int64(0)

In [15]:
#clean boxes

In [ ]:
df.columns
#Hours Studied
#Previous Score
#Extracurricular Activities
#Sleep Hours

# ------------ target --------------
#Performance Index

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [ ]:
limits = ""